#! /bin/zsh

mkdir desktop
xdg-user-dirs-update
XDG_DOWNLOAD_DIR=$(xdg-user-dir DOWNLOAD)

feh --bg-fill ~/.wallpapers/dark_wallpaper.png

if [ ! -d "$HOME/.icons" ]
then
    mkdir .icons
fi

if [ ! -d "$HOME/.icons/catppuccin-mocha-dark-cursors" ]
then
    wget -P "$XDG_DOWNLOAD_DIR" "https://github.com/catppuccin/cursors/releases/download/v2.0.0/catppuccin-mocha-dark-cursors.zip"
    unzip "$XDG_DOWNLOAD_DIR/catppuccin-mocha-dark-cursors.zip" "$HOME/.icons"
    rm "$XDG_DOWNLOAD_DIR/catppuccin-mocha-dark-cursors.zip"
fi

if [ ! -d "$HOME/.icons/capputtin-latte-light-cursors" ]
then
    wget -P "$XDG_DOWNLOAD_DIR" "https://github.com/catppuccin/cursors/releases/download/v2.0.0/catppuccin-latte-light-cursors.zip"
    unzip "$XDG_DOWNLOAD_DIR/catppuccin-latte-light-cursors.zip" "$HOME/.icons"
    rm "$XDG_DOWNLOAD_DIR/catppuccin-latte-light-cursors.zip"
fi

i3-msg restart
