# Configuration for picom

fading = true;
fade-delta = 5;
corner-radius = 5;
blur-method = "dual_kawase";
blur-strength = 2;
backend = "glx";
vsync = true;

rules: (
    {
        match = "class_g = 'Alacritty' || class_g = 'Polybar' || class_g = 'Rofi' || class_g = 'Code' || class_g = 'Zathura'";
        opacity = 0.9;
    },
    {
        match = "!focused";
        dim = 0.2;
    },
    {
        match = "fullscreen = true";
        corner-radius = 0;
    },
    {
        match = "window_type = 'popup_menu' || window_type = 'utility'";
        dim = 0;
        blur-background = false;
    }
)
