# Configuration file for Alacritty

import = [ "~/.config/alacritty/colors.toml", ]

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }
bold_italic = { family = "JetBrains Mono", style = "Bold Italic" }
size = 10
offset = { x = 0, y = 0 }

[cursor]
style = { shape = "Underline", blinking = "On" }

[mouse]
hide_when_typing = true
