[general]
import = [ "catppuccin_mocha.toml" ]

[window]
padding = { x = 5, y = 0 }

[font]
normal = { family = "IBM Plex Mono", style = "Regular" }
bold = { family = "IBM Plex Mono", style = "Bold" }
italic = { family = "IBM Plex Mono", style = "Italic" }
bold_italic = { family = "IBM Plex Mono", style = "Bold Italic" }
size = 10

[bell]
duration = 200
color = "#f38ba8"

[cursor]
style = { shape = "Underline", blinking = "Always" }

[terminal]
shell = "/usr/bin/zsh"

[mouse]
hide_when_typing = true
