; Configuration for Polybar.

[colors]
bg = #100f0f
bg_2 = #1c1b1a
ui = #282726
ui_2 = #343331
ui_3 = #403e3c
tx_3 = #575653
tx_2 = #878580
tx = #cecdc3
re_2 = #af3029
or_2 = #bc5215
ye_2 = #ad8301
gr_2 = #66800b
cy_2 = #24837b
bl_2 = #205ea6
pu_2 = #5e409d
ma_2 = #a02f6f
re = #d14d41
or = #da702c
ye = #d0a215
gr = #879a39
cy = #3aa99f
bl = #4385be
pu = #8b7ec8
ma = #ce5d97

[bar/bar]
override-redirect = true
width = 1900
height = 25
offset-x = 10
offset-y = 10
background = ${colors.bg}
foreground = ${colors.fg}
padding = 1
module-margin = 1
font-0 = JetBrains Mono:size=10;2
modules-left = xworkspaces
modules-center = date
modules-right = pulseaudio cpu memory fs_ssd fs_hdd
separator = " "
wm-name = i3
locale = en_GB.UTF-8
enable-ipc = true

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-foreground = ${colors.or}
label-active-padding = 1

label-occupied = %name%
label-occupied-foreground = ${colors.gr}
label-occupied-padding = 1

label-urgent = %name%
label-urgent-foreground = ${colors.re}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.ui_3}
label-empty-padding = 1

[module/date]
type = internal/date
date = %Y-%m-%d
time = %H:%M

label = %date% %time%
label-foreground = ${colors.cy}

[module/pulseaudio]
type = internal/pulseaudio

format-volume = <label-volume>
format-volume-foreground = ${colors.cy}
format-volume-prefix = "VOL "
format-volume-prefix-foreground = ${colors.gr}
format-volume-suffix = %
format-volume-suffix-foreground = ${colors.or}

format-muted = <label-muted>
format-muted-foreground = ${colors.ui_3}
format-muted-prefix = "VOL "
format-muted-prefix-foreground = ${colors.gr}
format-muted-suffix = %
format-muted-suffix-foreground = ${colors.or}

label-volume = %percentage:2%
label-muted = " 0"

[module/cpu]
type = internal/cpu

format = <label>
format-foreground = ${colors.cy}
format-prefix = "CPU "
format-prefix-foreground = ${colors.gr}
format-suffix = %
format-suffix-foreground = ${colors.or}

label = %percentage:2%

[module/memory]
type = internal/memory

format = <label>
format-foreground = ${colors.cy}
format-prefix = "RAM "
format-prefix-foreground = ${colors.gr}
format-suffix = %
format-suffix-foreground = ${colors.or}

label = %percentage_used:2%

[module/fs_ssd]
type = internal/fs

mount-0 = /

format-mounted = <label-mounted>
format-mounted-foreground = ${colors.cy}
format-mounted-prefix = "SSD "
format-mounted-prefix-foreground = ${colors.gr}
format-mounted-suffix = %
format-mounted-suffix-foreground = ${colors.or}

format-unmounted = <label-unmounted>
format-unmounted-foreground = ${colors.cy}
format-unmounted-prefix = "SSD "
format-unmounted-prefix-foreground = ${colors.gr}
format-unmounted-suffix = %
format-unmounted-suffix-foreground = ${colors.or}

label-mounted = %percentage_used:2%
label-unmounted = " 0"

[module/fs_hdd]
type = internal/fs

mount-0 = /media/storage

format-mounted = <label-mounted>
format-mounted-foreground = ${colors.cy}
format-mounted-prefix = "HDD "
format-mounted-prefix-foreground = ${colors.gr}
format-mounted-suffix = %
format-mounted-suffix-foreground = ${colors.or}

format-unmounted = <label-unmounted>
format-unmounted-foreground = ${colors.cy}
format-unmounted-prefix = "HDD "
format-unmounted-prefix-foreground = ${colors.gr}
format-unmounted-suffix = %
format-unmounted-suffix-foreground = ${colors.or}

label-mounted = %percentage_used:2%
label-unmounted = " 0"
